@startuml User

class User {
    # userId: string
    # username: string
    # password: string
    # email: string
    # phone: string

    + User(userId: string, username: string, password: string, email: string)

    + getUserId(): string
    + getUsername(): string
    + getPassword(): string
    + getEmail(): string
    + getPhone(): string

    + setUsername(username: string): void
    + setPassword(password: string): void
    + setEmail(email: string): void
    + setPhone(phone: string): void

    + login(): boolean
    + logout(): void

    + createGroup(): void
    + joinGroup(groupId: int): void
    + leaveGroup(groupId: int): void
    + viewGroupMembers(groupId: int): void
    + viewGroupSettings(groupId: int): void

    + likePost(postId: int): void
    + unlikePost(postId: int): void
    + commentPost(postId: int, comment: string): void
    + removeComment(commentId: int): void
    + interactWithPost(postId: int, interaction): void
}

@enduml