@startuml GroupFeed

!include groupPost.plantuml

class GroupFeed {
    - groupFeedId: string
    - groupId: string
    - groupMemberId: string

    - gropPosts: GroupPost[]

    + GroupFeed(groupId: string, groupMemberId: string)

    + getGroupFeedId(): string
    + getGroupId(): string
    + getGroupMemberId(): string
    + getGroupPosts(): GroupPost[]

    + filterFeed(filter) : void
}

GroupFeed "1" o-- "0..*" GroupPost : contains

@endulm