@startuml GroupPost

!include ../post/post.plantuml

class GroupPost extends Post {
    - groupId: string

    + GroupPost(postId: string, postOwnerId: string, groupId: string, content)

    + getGroupId(): string

    + hideGroupPost(): void
    + unhideGroupPost(): void
    + pinGroupPost(): void
    + unpinGroupPost(): void
}

@enduml